name = "uri_ada"
description = "Processing of URI strings"
version = "2.0"
licenses = "MIT"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

tags = ["uri", "url", "utility"]
